# Copyright (c) 2022 Alix Routhier-Lalonde. Licence included in root of package.

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/PyCQA/pylint
    rev: v2.14.4
    hooks:
    -   id: pylint
